/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: iQuote API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.models

import com.squareup.moshi.Json

/**
 * 
 * @property message 
 * @property status
 * @property data
 */
data class AuthRegisterResponse (
        @Json(name = "message") @field:Json(name = "message") var message: Message? = null,
        @Json(name = "status") @field:Json(name = "status") var status: Boolean? = null,
        @Json(name = "data") @field:Json(name = "data") var data: User? = null
)

