/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: iQuote API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.models

import com.squareup.moshi.Json
import java.math.BigDecimal

/**
 * 
 * @property id 
 * @property userId 
 * @property registeredName 
 * @property serviceName 
 * @property NZBN 
 * @property registeredAddress 
 * @property serviceAddress 
 * @property serviceRadius 
 * @property facebookLink 
 * @property instagramLink 
 * @property createdAt 
 * @property updatedAt 
 * @property phone 
 * @property images 
 * @property services 
 */
data class Business (
        @Json(name = "id") @field:Json(name = "id") var id: Int? = null,
        @Json(name = "user_id") @field:Json(name = "user_id") var userId: Int? = null,
        @Json(name = "registered_name") @field:Json(name = "registered_name") var registeredName: String? = null,
        @Json(name = "service_name") @field:Json(name = "service_name") var serviceName: String? = null,
        @Json(name = "NZBN") @field:Json(name = "NZBN") var NZBN: String? = null,
        @Json(name = "registered_address") @field:Json(name = "registered_address") var registeredAddress: String? = null,
        @Json(name = "service_address") @field:Json(name = "service_address") var serviceAddress: String? = null,
        @Json(name = "service_radius") @field:Json(name = "service_radius") var serviceRadius: Double? = null,
        @Json(name = "facebook_link") @field:Json(name = "facebook_link") var facebookLink: String? = null,
        @Json(name = "instagram_link") @field:Json(name = "instagram_link") var instagramLink: String? = null,
        @Json(name = "created_at") @field:Json(name = "created_at") var createdAt: String? = null,
        @Json(name = "updated_at") @field:Json(name = "updated_at") var updatedAt: String? = null,
        @Json(name = "phone") @field:Json(name = "phone") var phone: String? = null,
        @Json(name = "images") @field:Json(name = "images") var images: List<Image>? = null,
        @Json(name = "services") @field:Json(name = "services") var services: List<Service>? = null
)

