/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: iQuote API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.models

import com.squareup.moshi.Json

/**
 * 
 * @property id 
 * @property deviceId 
 * @property deviceType 
 * @property devicePushToken 
 * @property userId 
 * @property accessToken 
 * @property accessTokenExpiresAt 
 * @property latestIpAddress 
 * @property createdAt 
 * @property updatedAt 
 */
data class Device (
        @Json(name = "id") @field:Json(name = "id") var id: Int? = null,
        @Json(name = "device_id") @field:Json(name = "device_id") var deviceId: String? = null,
        @Json(name = "device_type") @field:Json(name = "device_type") var deviceType: String? = null,
        @Json(name = "device_push_token") @field:Json(name = "device_push_token") var devicePushToken: String? = null,
        @Json(name = "user_id") @field:Json(name = "user_id") var userId: Int? = null,
        @Json(name = "access_token") @field:Json(name = "access_token") var accessToken: String? = null,
        @Json(name = "access_token_expires_at") @field:Json(name = "access_token_expires_at") var accessTokenExpiresAt: String? = null,
        @Json(name = "latest_ip_address") @field:Json(name = "latest_ip_address") var latestIpAddress: String? = null,
        @Json(name = "created_at") @field:Json(name = "created_at") var createdAt: String? = null,
        @Json(name = "updated_at") @field:Json(name = "updated_at") var updatedAt: String? = null
)

