/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: iQuote API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.models

import com.squareup.moshi.Json

/**
 * 
 * @property id 
 * @property url 
 * @property thumbnailUrl 
 * @property category 
 */
data class Image (
        @Json(name = "id") @field:Json(name = "id") var id: Int? = null,
        @Json(name = "url") @field:Json(name = "url") var url: String? = null,
        @Json(name = "thumbnail_url") @field:Json(name = "thumbnail_url") var thumbnailUrl: String? = null,
        @Json(name = "category") @field:Json(name = "category") var category: String? = null
)

