/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Oxygen Sandbox Backend API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.models

import com.squareup.moshi.Json

/**
 * 
 * @property email 
 * @property password 
 * @property deviceId 
 * @property deviceType 
 * @property devicePushToken 
 */
data class Login (
        @Json(name = "email") @field:Json(name = "email") var email: String? = null,
        @Json(name = "password") @field:Json(name = "password") var password: String? = null,
        @Json(name = "device_id") @field:Json(name = "device_id") var deviceId: String? = null,
        @Json(name = "device_type") @field:Json(name = "device_type") var deviceType: String? = null,
        @Json(name = "device_push_token") @field:Json(name = "device_push_token") var devicePushToken: String? = null
)

