/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: iQuote API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.models

import com.squareup.moshi.Json
import java.math.BigDecimal

/**
 * 
 * @property currentPage 
 * @property perPage 
 * @property to 
 */
data class Paginator (
        @Json(name = "current_page") @field:Json(name = "current_page") var currentPage: BigDecimal? = null,
        @Json(name = "per_page") @field:Json(name = "per_page") var perPage: BigDecimal? = null,
        @Json(name = "to") @field:Json(name = "to") var to: BigDecimal? = null
)

