/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Oxygen Sandbox Backend API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.models

import com.squareup.moshi.Json

/**
 * 
 * @property password 
 * @property currentPassword 
 * @property passwordConfirmation 
 */
data class PasswordEdit (
        @Json(name = "password") @field:Json(name = "password") var password: String? = null,
        @Json(name = "current_password") @field:Json(name = "current_password") var currentPassword: String? = null,
        @Json(name = "password_confirmation") @field:Json(name = "password_confirmation") var passwordConfirmation: String? = null
)

