/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: iQuote API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.models

import com.squareup.moshi.Json

/**
 * 
 * @property id 
 * @property userId 
 * @property businessId 
 * @property serviceId 
 * @property location 
 * @property date 
 * @property description 
 * @property flag 
 * @property createdAt 
 * @property updatedAt 
 * @property client 
 * @property business 
 * @property service 
 */
data class Quote (
        @Json(name = "id") @field:Json(name = "id") var id: Int? = null,
        @Json(name = "user_id") @field:Json(name = "user_id") var userId: Int? = null,
        @Json(name = "business_id") @field:Json(name = "business_id") var businessId: Int? = null,
        @Json(name = "service_id") @field:Json(name = "service_id") var serviceId: Int? = null,
        @Json(name = "location") @field:Json(name = "location") var location: String? = null,
        @Json(name = "date") @field:Json(name = "date") var date: String? = null,
        @Json(name = "description") @field:Json(name = "description") var description: String? = null,
        @Json(name = "flag") @field:Json(name = "flag") var flag: Boolean? = null,
        @Json(name = "created_at") @field:Json(name = "created_at") var createdAt: String? = null,
        @Json(name = "updated_at") @field:Json(name = "updated_at") var updatedAt: String? = null,
        @Json(name = "client") @field:Json(name = "client") var client: User? = null,
        @Json(name = "business") @field:Json(name = "business") var business: User? = null,
        @Json(name = "service") @field:Json(name = "service") var service: Service? = null
)

