/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Oxygen Sandbox Backend API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.models

import com.squareup.moshi.Json

/**
 * 
 * @property ABOUTUS 
 * @property PRIVACYPOLICY 
 * @property TERMSANDCONDITIONS 
 */
data class Settings (
        @Json(name = "ABOUT_US") @field:Json(name = "ABOUT_US") var ABOUTUS: String? = null,
        @Json(name = "PRIVACY_POLICY") @field:Json(name = "PRIVACY_POLICY") var PRIVACYPOLICY: String? = null,
        @Json(name = "TERMS_AND_CONDITIONS") @field:Json(name = "TERMS_AND_CONDITIONS") var TERMSANDCONDITIONS: String? = null
)

