/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: iQuote API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.models

import com.squareup.moshi.Json

/**
 * 
 * @property id 
 * @property key 
 * @property value 
 * @property createdAt 
 * @property updatedAt 
 */
data class Setting (
        @Json(name = "id") @field:Json(name = "id") var id: Int? = null,
        @Json(name = "key") @field:Json(name = "key") var key: String? = null,
        @Json(name = "value") @field:Json(name = "value") var value: String? = null,
        @Json(name = "created_at") @field:Json(name = "created_at") var createdAt: String? = null,
        @Json(name = "updated_at") @field:Json(name = "updated_at") var updatedAt: String? = null
)

