/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: iQuote API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.models

import com.squareup.moshi.Json
import java.math.BigDecimal

data class User(
    @Json(name = "ID") @field:Json(name = "ID") var id: String? = null,
    @Json(name = "CreatedAt") @field:Json(name = "CreatedAt") var createdAt: String? = null,
    @Json(name = "UpdatedAt") @field:Json(name = "UpdatedAt") var updatedAt: String? = null,
    @Json(name = "DeletedAt") @field:Json(name = "DeletedAt") var deletedAt: String? = null,
    @Json(name = "MobileNo") @field:Json(name = "MobileNo") var mobileNo: String? = null,
    @Json(name = "DefaultLanguage") @field:Json(name = "DefaultLanguage") var defaultLanguage: String? = null,
    @Json(name = "Email") @field:Json(name = "Email") var email: String? = null,
    @Json(name = "FullName") @field:Json(name = "FullName") var fullName: String? = null,
    @Json(name = "DOB") @field:Json(name = "DOB") var dob: String? = null,
    @Json(name = "Role") @field:Json(name = "Role") var role: String? = null,
    @Json(name = "ProfilePicture") @field:Json(name = "ProfilePicture") var profilePicture: String? = null,
    @Json(name = "ProfileVideo") @field:Json(name = "ProfileVideo") var profileVideo: String? = null,
    @Json(name = "ProfileBanner") @field:Json(name = "ProfileBanner") var profileBanner: String? = null,
    @Json(name = "Preferences") @field:Json(name = "Preferences") var preferences: List<Preference>? = null,
    @Json(name = "Auth0Ref") @field:Json(name = "Auth0Ref") var authReference: String? = null,
    @Json(name = "Verified") @field:Json(name = "Verified") var verified: Boolean? = null
)

