/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: iQuote API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.models

import com.squareup.moshi.Json
import java.math.BigDecimal

/**
 * 
 * @property id 
 * @property uuid 
 * @property name 
 * @property phone 
 * @property email 
 * @property avatarUrl 
 * @property timezone 
 * @property type 
 * @property signupError 
 * @property business 
 * @property services 
 * @property accessToken 
 */
data class User (
        @Json(name = "id") @field:Json(name = "id") var id: Int? = null,
        @Json(name = "uuid") @field:Json(name = "uuid") var uuid: String? = null,
        @Json(name = "name") @field:Json(name = "name") var name: String? = null,
        @Json(name = "phone") @field:Json(name = "phone") var phone: String? = null,
        @Json(name = "email") @field:Json(name = "email") var email: String? = null,
        @Json(name = "avatar_url") @field:Json(name = "avatar_url") var avatarUrl: String? = null,
        @Json(name = "timezone") @field:Json(name = "timezone") var timezone: String? = null,
        @Json(name = "type") @field:Json(name = "type") var type: Int? = null,
        @Json(name = "signup_error") @field:Json(name = "signup_error") var signupError: String? = null,
        @Json(name = "business") @field:Json(name = "business") var business: Business? = null,
        @Json(name = "services") @field:Json(name = "services") var services: String? = null,
        @Json(name = "access_token") @field:Json(name = "access_token") var accessToken: String? = null
)

