/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: iQuote API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.apis

import sl.com.eightdigitz.client.models.BusinessServicesListResponse
import io.reactivex.Single
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface BusinessServicesApi {
    /**
     * List
     * This endpoint returns paginated list of the entity
     * The endpoint is owned by integration service owner
     * @param accept &#x60;application/json&#x60; (required)
     * @param q text to search  (optional)
     */
    @Headers(
        "X-Operation-Id: business_services_get_list",
        "Content-Type: application/json"
    )
    @GET("services")
    fun businessServicesGetList(
        @retrofit2.http.Query("q") q: String?
    ): Single<BusinessServicesListResponse>

}
