/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Oxygen Sandbox Backend API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.apis

import sl.com.eightdigitz.client.models.ChatUploadFileResponse
import io.reactivex.Single
import okhttp3.MultipartBody
import retrofit2.http.POST
import retrofit2.http.Part

@JvmSuppressWildcards
interface ChatApi {
    /**
     * Upload file
     *
     * The endpoint is owned by integration service owner
     * @param file Supported file types: doc,pdf,docx,jpg,jpeg,png,gif,mpga,mp3,wav,mp4,mov,ogg,qt (required)
     * @param thumbnail Supported file types: png (optional)
     */
    @retrofit2.http.Multipart
    @POST("chat/files")
    fun chatFilesPost(
        @Part image: MultipartBody.Part,
        @Part thumb: MultipartBody.Part?
    ): Single<ChatUploadFileResponse>

}
