/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: iQuote API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.apis

import sl.com.eightdigitz.client.models.SuccessResponse
import io.reactivex.Single
import retrofit2.http.Headers
import retrofit2.http.POST

@JvmSuppressWildcards
interface ForgotPasswordApi {
    /**
     * Reset Password
     *
     * The endpoint is owned by integration service owner
     * @param accept &#x60;application/json&#x60; (required)
     * @param email Email (required)
     */
    @retrofit2.http.FormUrlEncoded
    @Headers(
        "X-Operation-Id: forgotpassword_post_reset_password"
    )
    @POST("password/email")
    fun forgotpasswordPostResetPassword(
        @retrofit2.http.Field("email") email: String
    ): Single<SuccessResponse>

}
