/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: iQuote API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.apis

import sl.com.eightdigitz.client.models.SuccessResponse
import io.reactivex.Single
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface GuestApi {
    /**
     * Guest Settings
     * Guest settings and parameters
     * The endpoint is owned by integration service owner
     * @param accept &#x60;application/json&#x60; (required)
     */
    @Headers(
        "X-Operation-Id: guest_get_guest_settings",
        "Content-Type: application/json"
    )
    @GET("guests")
    fun guestGetGuestSettings(
    ): Single<SuccessResponse>

}
