/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: iQuote API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.apis

import sl.com.eightdigitz.client.models.ProfileMyProfileResponse
import sl.com.eightdigitz.client.models.ProfileUpdateMyAvatarResponse
import sl.com.eightdigitz.client.models.ProfileUpdateResponse
import sl.com.eightdigitz.client.models.SuccessResponse
import io.reactivex.Single
import okhttp3.MultipartBody
import okhttp3.RequestBody
import retrofit2.http.*

@JvmSuppressWildcards
interface ProfileApi {
    /**
     * My Profile
     * Get currently logged in user's profile
     * The endpoint is owned by integration service owner
     * @param accept Set to &#x60;application/json&#x60; (required)
     */
    @Headers(
        "X-Operation-Id: profile_get_my_profile",
        "Content-Type: application/json"
    )
    @GET("profile")
    fun profileGetMyProfile(
    ): Single<ProfileMyProfileResponse>

    /**
     * Update My Avatar
     *
     * The endpoint is owned by integration service owner
     * @param image Image (required)
     * @param accept Set to &#x60;application/json&#x60; (required)
     */
    @retrofit2.http.Multipart
    @Headers(
        "X-Operation-Id: profile_post_update_my_avatar"
    )
    @POST("avatar")
    fun profilePostUpdateMyAvatar(
        @Part image: MultipartBody.Part
    ): Single<ProfileUpdateMyAvatarResponse>

    /**
     * verify phone
     * This endpoint checks received verification code
     * The endpoint is owned by integration service owner
     * @param accept &#x60;application/json&#x60; (required)
     * @param code received code (required)
     */
    @retrofit2.http.FormUrlEncoded
    @Headers(
        "X-Operation-Id: profile_post_verify_phone"
    )
    @POST("phone/verify")
    fun profilePostVerifyPhone(
        @retrofit2.http.Field("code") code: String
    ): Single<SuccessResponse>

    /**
     * Update
     * This endpoint updates the phone number and send verification code
     * The endpoint is owned by integration service owner
     * @param accept &#x60;application/json&#x60; (required)
     * @param name name to be updated (required)
     * @param email email to be updated (required)
     */
    @retrofit2.http.FormUrlEncoded
    @Headers(
        "X-Operation-Id: profile_put_update"
    )
    @PUT("profile")
    fun profilePutUpdate(
        @retrofit2.http.Field("name") name: String,
        @retrofit2.http.Field("email") email: String
    ): Single<ProfileUpdateResponse>

}
