/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: iQuote API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.apis

import sl.com.eightdigitz.client.models.QuotesListResponse
import sl.com.eightdigitz.client.models.QuotesSaveResponse
import sl.com.eightdigitz.client.models.QuotesViewResponse
import io.reactivex.Single
import retrofit2.http.GET
import retrofit2.http.Headers
import retrofit2.http.POST

@JvmSuppressWildcards
interface QuotesApi {
    /**
     * List
     * This endpoint returns paginated list of the entity
     * The endpoint is owned by integration service owner
     * @param accept &#x60;application/json&#x60; (required)
     * @param q text to search  (optional)
     */
    @Headers(
        "X-Operation-Id: quotes_get_list",
        "Content-Type: application/json"
    )
    @GET("quotes")
    fun quotesGetList(
        @retrofit2.http.Query("q") q: String?
    ): Single<QuotesListResponse>

    /**
     * view
     * This endpoint view requested entity
     * The endpoint is owned by integration service owner
     * @param accept &#x60;application/json&#x60; (required)
     * @param id ID of the entity (required)
     */
    @Headers(
        "X-Operation-Id: quotes_get_view",
        "Content-Type: application/json"
    )
    @GET("quotes/{id}")
    fun quotesGetView(
        @retrofit2.http.Path("id") id: String
    ): Single<QuotesViewResponse>

    /**
     * Save
     * This endpoint save the record in DB
     * The endpoint is owned by integration service owner
     * @param accept &#x60;application/json&#x60; (required)
     * @param serviceId id of the service quote belongs (required)
     * @param location address of the client (required)
     * @param date date for the service (required)
     * @param businessId id of the business to send the quote (optional)
     * @param description service description (optional)
     */
    @retrofit2.http.FormUrlEncoded
    @Headers(
        "X-Operation-Id: quotes_post_save"
    )
    @POST("quotes")
    fun quotesPostSave(
        @retrofit2.http.Field("service_id") serviceId: String,
        @retrofit2.http.Field("location") location: String,
        @retrofit2.http.Field("date") date: String,
        @retrofit2.http.Field("business_id") businessId: String?,
        @retrofit2.http.Field("description") description: String?
    ): Single<QuotesSaveResponse>

}
