/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: iQuote API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.apis

import sl.com.eightdigitz.client.models.SuccessResponse
import io.reactivex.Single
import retrofit2.http.Headers
import retrofit2.http.POST

@JvmSuppressWildcards
interface ResetPasswordApi {
    /**
     * Reset password
     * Rest password with the token
     * The endpoint is owned by integration service owner
     * @param accept &#x60;application/json&#x60; (required)
     * @param email email of the user (required)
     * @param token token received (required)
     * @param password Password. Must be at least 8 characters. (required)
     * @param passwordConfirmation Confirm password. Must be at least 8 characters. (required)
     */
    @retrofit2.http.FormUrlEncoded
    @Headers(
        "X-Operation-Id: resetpassword_post_reset_password"
    )
    @POST("password/reset")
    fun resetpasswordPostResetPassword(
        @retrofit2.http.Field("email") email: String,
        @retrofit2.http.Field("token") token: String,
        @retrofit2.http.Field("password") password: String,
        @retrofit2.http.Field("password_confirmation") passwordConfirmation: String
    ): Single<SuccessResponse>

}
