/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: iQuote API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.apis

import sl.com.eightdigitz.client.models.SettingsGetSettingsResponse
import sl.com.eightdigitz.client.models.SuccessResponse
import io.reactivex.Single
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface SettingsApi {
    /**
     * Get Setting
     * Returns the value of a single app setting requested by key.
     * The endpoint is owned by integration service owner
     * @param key Key of the setting (required)
     * @param accept Set to &#x60;application/json&#x60; (required)
     */
    @Headers(
        "X-Operation-Id: settings_get_get_setting",
        "Content-Type: application/json"
    )
    @GET("settings/{key}")
    fun settingsGetGetSetting(
        @retrofit2.http.Path("key") key: String
    ): Single<SuccessResponse>

    /**
     * Get Settings
     * Returns all app settings. Each setting value is identified by the respective key.
     * The endpoint is owned by integration service owner
     * @param accept &#x60;application/json&#x60; (required)
     */
    @Headers(
        "X-Operation-Id: settings_get_get_settings",
        "Content-Type: application/json"
    )
    @GET("settings")
    fun settingsGetGetSettings(): Single<SettingsGetSettingsResponse>

}
