/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Oxygen Sandbox Backend API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.client.apis

import sl.com.eightdigitz.client.models.UserListResponse
import io.reactivex.Single
import retrofit2.http.GET
import retrofit2.http.Headers

@JvmSuppressWildcards
interface UserApi {
    /**
     * List
     *
     * The endpoint is owned by integration service owner
     * @param q Query to filter the list (optional)
     * @param page query (optional)
     * @param perPage Items per page (optional)
     */
    @Headers(
        "Content-Type: application/x-www-form-urlencoded"
    )
    @GET("users")
    fun usersGet(
        @retrofit2.http.Query("q") q: String?,
        @retrofit2.http.Query("page") page: Int?,
        @retrofit2.http.Query("per_page") perPage: Int?
    ): Single<UserListResponse>

}
