/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: iQuote API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.core.presentation.model

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize


/**
 *
 * @property id
 * @property name
 */

@Parcelize
data class PService(
    var id: Int? = null,
    var name: String? = null
): Parcelable

