/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Oxygen Sandbox Backend API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.chat.domain.model

data class DMessageFile (
        var uuid: String? = null,
        var url: String? = null,
        var thumbnailUrl: String? = null,
        var type: String? = null
)

