/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: iQuote API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.core.model.presentation

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @property id
 * @property userId
 * @property registeredName
 * @property serviceName
 * @property NZBN
 * @property registeredAddress
 * @property serviceAddress
 * @property serviceRadius
 * @property facebookLink
 * @property instagramLink
 * @property createdAt
 * @property updatedAt
 * @property phone
 * @property images
 * @property services
 */

@Parcelize
data class PBusiness(
    var id: Int? = null,
    var userId: Int? = null,
    var registeredName: String? = null,
    var serviceName: String? = null,
    var NZBN: String? = null,
    var registeredAddress: String? = null,
    var serviceAddress: String? = null,
    var serviceRadius: Double? = null,
    var facebookLink: String? = null,
    var instagramLink: String? = null,
    var createdAt: String? = null,
    var updatedAt: String? = null,
    var phone: String? = null,
    var images: List<PImage>? = null,
    var services: List<PService>? = null
): Parcelable

