/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: iQuote API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package sl.com.eightdigitz.core.model.presentation

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

/**
 *
 * @property id
 * @property url
 * @property thumbnailUrl
 * @property category
 */

@Parcelize
data class PImage(
    var id: Int? = null,
    var url: String? = null,
    var thumbnailUrl: String? = null,
    var category: String? = null
): Parcelable

